name: Build and Push OpenSSL Container

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-openssl.yml'
      - 'generate_mldsa_key.sh'
      - 'generate_and_sign_slh_dsa.sh'

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Some accounts did not use a lowercase repository owner, so we need to ensure
      # that the repository owner is always in lowercase to be able to build the images.
      - name: Set lowercase GitHub owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Build and push base Docker image
        run: |
          docker buildx build \
            --tag ghcr.io/${REPO_OWNER_LC}/openssl-test-base:latest \
            --push \
            -f Dockerfile .
