name: Build and Push OpenSSL Container

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-openssl.yml'
      - 'generate_mldsa_key.sh'
      - 'generate_and_sign_slh_dsa.sh'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/openssl-mldsa:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/openssl-mldsa:latest
